### ISSUE TITLE
Bug: Player Spontaneously Ignites Upon successful curse burn

### ISSUE THREAD

**Issue by MajorPing5** [UMKC-GDC-Byte-Brigade/Themed-Horror-Game-Jam---2024#33]
When the player successfully burns the right item, without the timer hitting 0, there is a random chance that the player may retrieve the same burn effect as if the player ran out of time.

**Comment by vymmf** [comment]
Trigger for Bug: When the player initiates another playthrough after losing/winning and throwing an object into the fire. From what we can see in the Debug Log, the fire initiates when fire.Play(); happens in BurnTheItems.cs.

**Comment by vymmf** [comment]
Nothing major was changed to fixed this bug; I simply renamed the FireParticles child in Player to PlayerFireParticles and it worked fine
